stages:
- check
- build
- publish

code_quality:
  stage: check
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - cd $CI_PROJECT_DIR
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run --env SOURCE_CODE="$(pwd)" -v "$(pwd):/code" -v /var/run/docker.sock:/var/run/docker.sock "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]
  only:
    - branches
  except:
    variables:
      - $CODE_QUALITY_DISABLED

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --update make
    - apk add --update bash
    - make build
    - make check|grep -v 'warning'
