sudo: required
services:
  - docker

before_install:
  - gem install fpm package_cloud

script:
  - make test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then make push-deb; fi

notifications:
  email: docker@katagena.com
