#!/usr/bin/env bash

LATEST_VERSION="2.8"

if [ "$DOCKER_TAG" = "latest" ]; then
	ANSIBLEVERSION=$LATEST_VERSION
else
	ANSIBLEVERSION=$DOCKER_TAG
fi

BASE_IMAGE=stretch

docker build -t ${IMAGE_NAME} \
	--build-arg=BASE_IMAGE=$BASE_IMAGE \
	--build-arg=ANSIBLEVERSION=$ANSIBLEVERSION \
	--build-arg=DOCKER_TAG=$DOCKER_TAG \
	.
